version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/packages/eslint-config-javascript"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: npm
  directory: "/packages/eslint-config-jest"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  
- package-ecosystem: npm
  directory: "/packages/eslint-config-jsdoc"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/packages/eslint-config-typescript"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/packages/eslint-config-vue"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/packages/stylelint-config-scss"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
